--CREACION TABLAS DIRECCION Y RELACIONADOS
--DEPARTAMENTO
CREATE TABLE Departamento(
    IdDepartamento INTEGER NOT NULL PRIMARY KEY,
    Nombre VARCHAR(25) NOT NULL UNIQUE
    );
--MUNICIPIO

--DIRECCION